# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""gRPC stub implementations for weights service."""

from __future__ import annotations

import grpc

from . import weights_pb2 as weights__pb2


class WeightsServiceStub:
    """Stub class for the WeightsService."""

    def __init__(self, channel: grpc.Channel) -> None:
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishWeights = channel.unary_unary(
            "/cartridge.weights.v1.WeightsService/PublishWeights",
            request_serializer=weights__pb2.PublishWeightsRequest.SerializeToString,
            response_deserializer=weights__pb2.PublishWeightsResponse.FromString,
        )
        self.StreamWeights = channel.unary_stream(
            "/cartridge.weights.v1.WeightsService/StreamWeights",
            request_serializer=weights__pb2.WatchRunRequest.SerializeToString,
            response_deserializer=weights__pb2.WeightsBlob.FromString,
        )
        self.GetCurrent = channel.unary_unary(
            "/cartridge.weights.v1.WeightsService/GetCurrent",
            request_serializer=weights__pb2.GetCurrentRequest.SerializeToString,
            response_deserializer=weights__pb2.WeightsBlob.FromString,
        )


class WeightsServiceServicer:
    """Base class for server-side implementations."""

    async def PublishWeights(self, request, context):  # pragma: no cover - server side
        raise NotImplementedError("Method not implemented!")

    async def StreamWeights(self, request, context):  # pragma: no cover - server side
        raise NotImplementedError("Method not implemented!")

    async def GetCurrent(self, request, context):  # pragma: no cover - server side
        raise NotImplementedError("Method not implemented!")


def add_WeightsServiceServicer_to_server(servicer, server):  # pragma: no cover - server side
    rpc_method_handlers = {
        "PublishWeights": grpc.unary_unary_rpc_method_handler(
            servicer.PublishWeights,
            request_deserializer=weights__pb2.PublishWeightsRequest.FromString,
            response_serializer=weights__pb2.PublishWeightsResponse.SerializeToString,
        ),
        "StreamWeights": grpc.unary_stream_rpc_method_handler(
            servicer.StreamWeights,
            request_deserializer=weights__pb2.WatchRunRequest.FromString,
            response_serializer=weights__pb2.WeightsBlob.SerializeToString,
        ),
        "GetCurrent": grpc.unary_unary_rpc_method_handler(
            servicer.GetCurrent,
            request_deserializer=weights__pb2.GetCurrentRequest.FromString,
            response_serializer=weights__pb2.WeightsBlob.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "cartridge.weights.v1.WeightsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
