# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import weights_pb2 as proto_dot_weights_dot_weights__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/weights/weights_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class WeightsServiceStub(object):
    """WeightsService exposes APIs for publishing and consuming learner checkpoints.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishWeights = channel.unary_unary(
                '/cartridge.weights.v1.WeightsService/PublishWeights',
                request_serializer=proto_dot_weights_dot_weights__pb2.PublishWeightsRequest.SerializeToString,
                response_deserializer=proto_dot_weights_dot_weights__pb2.PublishWeightsResponse.FromString,
                _registered_method=True)
        self.StreamWeights = channel.unary_stream(
                '/cartridge.weights.v1.WeightsService/StreamWeights',
                request_serializer=proto_dot_weights_dot_weights__pb2.WatchRunRequest.SerializeToString,
                response_deserializer=proto_dot_weights_dot_weights__pb2.WeightsBlob.FromString,
                _registered_method=True)
        self.GetCurrent = channel.unary_unary(
                '/cartridge.weights.v1.WeightsService/GetCurrent',
                request_serializer=proto_dot_weights_dot_weights__pb2.GetCurrentRequest.SerializeToString,
                response_deserializer=proto_dot_weights_dot_weights__pb2.WeightsBlob.FromString,
                _registered_method=True)


class WeightsServiceServicer(object):
    """WeightsService exposes APIs for publishing and consuming learner checkpoints.
    """

    def PublishWeights(self, request, context):
        """PublishWeights promotes a new weight version for a run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamWeights(self, request, context):
        """StreamWeights streams subsequent versions for the requested run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrent(self, request, context):
        """GetCurrent returns the latest published version for the run.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeightsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishWeights,
                    request_deserializer=proto_dot_weights_dot_weights__pb2.PublishWeightsRequest.FromString,
                    response_serializer=proto_dot_weights_dot_weights__pb2.PublishWeightsResponse.SerializeToString,
            ),
            'StreamWeights': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamWeights,
                    request_deserializer=proto_dot_weights_dot_weights__pb2.WatchRunRequest.FromString,
                    response_serializer=proto_dot_weights_dot_weights__pb2.WeightsBlob.SerializeToString,
            ),
            'GetCurrent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrent,
                    request_deserializer=proto_dot_weights_dot_weights__pb2.GetCurrentRequest.FromString,
                    response_serializer=proto_dot_weights_dot_weights__pb2.WeightsBlob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cartridge.weights.v1.WeightsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cartridge.weights.v1.WeightsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeightsService(object):
    """WeightsService exposes APIs for publishing and consuming learner checkpoints.
    """

    @staticmethod
    def PublishWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cartridge.weights.v1.WeightsService/PublishWeights',
            proto_dot_weights_dot_weights__pb2.PublishWeightsRequest.SerializeToString,
            proto_dot_weights_dot_weights__pb2.PublishWeightsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/cartridge.weights.v1.WeightsService/StreamWeights',
            proto_dot_weights_dot_weights__pb2.WatchRunRequest.SerializeToString,
            proto_dot_weights_dot_weights__pb2.WeightsBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cartridge.weights.v1.WeightsService/GetCurrent',
            proto_dot_weights_dot_weights__pb2.GetCurrentRequest.SerializeToString,
            proto_dot_weights_dot_weights__pb2.WeightsBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
