# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weights.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rweights.proto\x12\x14\x63\x61rtridge.weights.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\x02\n\x15PublishWeightsRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x03\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t\x12\x14\n\x0c\x61rtifact_uri\x18\x04 \x01(\t\x12\x16\n\x0einline_payload\x18\x05 \x01(\x0c\x12K\n\x08metadata\x18\x06 \x03(\x0b\x32\x39.cartridge.weights.v1.PublishWeightsRequest.MetadataEntry\x12\x30\n\x0cpublished_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"L\n\x16PublishWeightsResponse\x12\x32\n\x07version\x18\x01 \x01(\x0b\x32!.cartridge.weights.v1.WeightsBlob\"8\n\x0fWatchRunRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x15\n\rreplay_latest\x18\x02 \x01(\x08\"#\n\x11GetCurrentRequest\x12\x0e\n\x06run_id\x18\x01 \x01(\t\"\x91\x02\n\x0bWeightsBlob\x12\x0e\n\x06run_id\x18\x01 \x01(\t\x12\x0c\n\x04step\x18\x02 \x01(\x03\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\t\x12\x14\n\x0c\x61rtifact_uri\x18\x04 \x01(\t\x12\x16\n\x0einline_payload\x18\x05 \x01(\x0c\x12\x41\n\x08metadata\x18\x06 \x03(\x0b\x32/.cartridge.weights.v1.WeightsBlob.MetadataEntry\x12\x30\n\x0cpublished_at\x18\x07 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xb4\x02\n\x0eWeightsService\x12k\n\x0ePublishWeights\x12+.cartridge.weights.v1.PublishWeightsRequest\x1a,.cartridge.weights.v1.PublishWeightsResponse\x12[\n\rStreamWeights\x12%.cartridge.weights.v1.WatchRunRequest\x1a!.cartridge.weights.v1.WeightsBlob0\x01\x12X\n\nGetCurrent\x12\'.cartridge.weights.v1.GetCurrentRequest\x1a!.cartridge.weights.v1.WeightsBlobB4Z2github.com/cartridge/weights/internal/pb;weightspbb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'weights_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z2github.com/cartridge/weights/internal/pb;weightspb'
  _PUBLISHWEIGHTSREQUEST_METADATAENTRY._options = None
  _PUBLISHWEIGHTSREQUEST_METADATAENTRY._serialized_options = b'8\001'
  _WEIGHTSBLOB_METADATAENTRY._options = None
  _WEIGHTSBLOB_METADATAENTRY._serialized_options = b'8\001'
  _PUBLISHWEIGHTSREQUEST._serialized_start=73
  _PUBLISHWEIGHTSREQUEST._serialized_end=366
  _PUBLISHWEIGHTSREQUEST_METADATAENTRY._serialized_start=319
  _PUBLISHWEIGHTSREQUEST_METADATAENTRY._serialized_end=366
  _PUBLISHWEIGHTSRESPONSE._serialized_start=368
  _PUBLISHWEIGHTSRESPONSE._serialized_end=444
  _WATCHRUNREQUEST._serialized_start=446
  _WATCHRUNREQUEST._serialized_end=502
  _GETCURRENTREQUEST._serialized_start=504
  _GETCURRENTREQUEST._serialized_end=539
  _WEIGHTSBLOB._serialized_start=542
  _WEIGHTSBLOB._serialized_end=815
  _WEIGHTSBLOB_METADATAENTRY._serialized_start=319
  _WEIGHTSBLOB_METADATAENTRY._serialized_end=366
  _WEIGHTSSERVICE._serialized_start=818
  _WEIGHTSSERVICE._serialized_end=1126
# @@protoc_insertion_point(module_scope)
