// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// source: proto/weights/weights.proto

package weightspb

import (
	"context"

	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the grpc package is being used.
const _ = grpc.SupportPackageIsVersion9

// WeightsServiceClient is the client API for WeightsService service.
type WeightsServiceClient interface {
	PublishWeights(ctx context.Context, in *PublishWeightsRequest, opts ...grpc.CallOption) (*PublishWeightsResponse, error)
	StreamWeights(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (WeightsService_StreamWeightsClient, error)
	GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*WeightsBlob, error)
}

type weightsServiceClient struct {
	cc grpc.ClientConnInterface
}

// NewWeightsServiceClient creates a new client for the WeightsService.
func NewWeightsServiceClient(cc grpc.ClientConnInterface) WeightsServiceClient {
	return &weightsServiceClient{cc}
}

func (c *weightsServiceClient) PublishWeights(ctx context.Context, in *PublishWeightsRequest, opts ...grpc.CallOption) (*PublishWeightsResponse, error) {
	out := new(PublishWeightsResponse)
	err := c.cc.Invoke(ctx, "/cartridge.weights.v1.WeightsService/PublishWeights", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightsServiceClient) StreamWeights(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (WeightsService_StreamWeightsClient, error) {
	stream, err := c.cc.NewStream(ctx, &WeightsService_ServiceDesc.Streams[0], "/cartridge.weights.v1.WeightsService/StreamWeights", opts...)
	if err != nil {
		return nil, err
	}
	x := &weightsServiceStreamWeightsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *weightsServiceClient) GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*WeightsBlob, error) {
	out := new(WeightsBlob)
	err := c.cc.Invoke(ctx, "/cartridge.weights.v1.WeightsService/GetCurrent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightsService_StreamWeightsClient is the client API for the StreamWeights method.
type WeightsService_StreamWeightsClient interface {
	Recv() (*WeightsBlob, error)
	grpc.ClientStream
}

type weightsServiceStreamWeightsClient struct {
	grpc.ClientStream
}

func (x *weightsServiceStreamWeightsClient) Recv() (*WeightsBlob, error) {
	m := new(WeightsBlob)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// WeightsServiceServer is the server API for WeightsService service.
type WeightsServiceServer interface {
	PublishWeights(context.Context, *PublishWeightsRequest) (*PublishWeightsResponse, error)
	StreamWeights(*WatchRunRequest, WeightsService_StreamWeightsServer) error
	GetCurrent(context.Context, *GetCurrentRequest) (*WeightsBlob, error)
	mustEmbedUnimplementedWeightsServiceServer()
}

// UnimplementedWeightsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedWeightsServiceServer struct{}

func (UnimplementedWeightsServiceServer) PublishWeights(context.Context, *PublishWeightsRequest) (*PublishWeightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishWeights not implemented")
}
func (UnimplementedWeightsServiceServer) StreamWeights(*WatchRunRequest, WeightsService_StreamWeightsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamWeights not implemented")
}
func (UnimplementedWeightsServiceServer) GetCurrent(context.Context, *GetCurrentRequest) (*WeightsBlob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrent not implemented")
}
func (UnimplementedWeightsServiceServer) mustEmbedUnimplementedWeightsServiceServer() {}

// UnsafeWeightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeightsServiceServer will
// result in compilation errors.
type UnsafeWeightsServiceServer interface {
	mustEmbedUnimplementedWeightsServiceServer()
}

// RegisterWeightsServiceServer registers the service implementation with the gRPC server.
func RegisterWeightsServiceServer(s grpc.ServiceRegistrar, srv WeightsServiceServer) {
	s.RegisterService(&WeightsService_ServiceDesc, srv)
}

func _WeightsService_PublishWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServiceServer).PublishWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cartridge.weights.v1.WeightsService/PublishWeights",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServiceServer).PublishWeights(ctx, req.(*PublishWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeightsService_StreamWeights_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WeightsServiceServer).StreamWeights(m, &weightsServiceStreamWeightsServer{stream})
}

type WeightsService_StreamWeightsServer interface {
	Send(*WeightsBlob) error
	grpc.ServerStream
}

type weightsServiceStreamWeightsServer struct {
	grpc.ServerStream
}

func (x *weightsServiceStreamWeightsServer) Send(m *WeightsBlob) error {
	return x.ServerStream.SendMsg(m)
}

func _WeightsService_GetCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServiceServer).GetCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cartridge.weights.v1.WeightsService/GetCurrent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServiceServer).GetCurrent(ctx, req.(*GetCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeightsService_ServiceDesc is the grpc.ServiceDesc for WeightsService service.
var WeightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cartridge.weights.v1.WeightsService",
	HandlerType: (*WeightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishWeights",
			Handler:    _WeightsService_PublishWeights_Handler,
		},
		{
			MethodName: "GetCurrent",
			Handler:    _WeightsService_GetCurrent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWeights",
			Handler:       _WeightsService_StreamWeights_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/weights/weights.proto",
}
