// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/weights/weights.proto

package weightspb

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishWeightsRequest carries learner output metadata.
type PublishWeightsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          int64                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ArtifactUri   string                 `protobuf:"bytes,4,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	InlinePayload []byte                 `protobuf:"bytes,5,opt,name=inline_payload,json=inlinePayload,proto3" json:"inline_payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
}

func (x *PublishWeightsRequest) Reset() {
	*x = PublishWeightsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWeightsRequest) ProtoMessage() {}

func (x *PublishWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWeightsRequest.ProtoReflect.Descriptor instead.
func (*PublishWeightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{0}
}

func (x *PublishWeightsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PublishWeightsRequest) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *PublishWeightsRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PublishWeightsRequest) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *PublishWeightsRequest) GetInlinePayload() []byte {
	if x != nil {
		return x.InlinePayload
	}
	return nil
}

func (x *PublishWeightsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublishWeightsRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// PublishWeightsResponse acknowledges a publication.
type PublishWeightsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version *WeightsBlob `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *PublishWeightsResponse) Reset() {
	*x = PublishWeightsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishWeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWeightsResponse) ProtoMessage() {}

func (x *PublishWeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWeightsResponse.ProtoReflect.Descriptor instead.
func (*PublishWeightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{1}
}

func (x *PublishWeightsResponse) GetVersion() *WeightsBlob {
	if x != nil {
		return x.Version
	}
	return nil
}

// WatchRunRequest opens a stream for updates.
type WatchRunRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId        string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ReplayLatest bool   `protobuf:"varint,2,opt,name=replay_latest,json=replayLatest,proto3" json:"replay_latest,omitempty"`
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WatchRunRequest) GetReplayLatest() bool {
	if x != nil {
		return x.ReplayLatest
	}
	return false
}

// GetCurrentRequest fetches the latest version.
type GetCurrentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
}

func (x *GetCurrentRequest) Reset() {
	*x = GetCurrentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRequest) ProtoMessage() {}

func (x *GetCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRequest) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// WeightsBlob represents a published manifest.
type WeightsBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          int64                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ArtifactUri   string                 `protobuf:"bytes,4,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	InlinePayload []byte                 `protobuf:"bytes,5,opt,name=inline_payload,json=inlinePayload,proto3" json:"inline_payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
}

func (x *WeightsBlob) Reset() {
	*x = WeightsBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightsBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightsBlob) ProtoMessage() {}

func (x *WeightsBlob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightsBlob.ProtoReflect.Descriptor instead.
func (*WeightsBlob) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{4}
}

func (x *WeightsBlob) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WeightsBlob) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *WeightsBlob) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *WeightsBlob) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *WeightsBlob) GetInlinePayload() []byte {
	if x != nil {
		return x.InlinePayload
	}
	return nil
}

func (x *WeightsBlob) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WeightsBlob) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// PublishWeightsRequest_MetadataEntry is the map entry type for Metadata field.
type PublishWeightsRequest_MetadataEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PublishWeightsRequest_MetadataEntry) Reset() {
	*x = PublishWeightsRequest_MetadataEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PublishWeightsRequest_MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWeightsRequest_MetadataEntry) ProtoMessage() {}

func (x *PublishWeightsRequest_MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWeightsRequest_MetadataEntry.ProtoReflect.Descriptor instead.
func (*PublishWeightsRequest_MetadataEntry) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{0, 0}
}

func (x *PublishWeightsRequest_MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PublishWeightsRequest_MetadataEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// WeightsBlob_MetadataEntry is the map entry type for Metadata field.
type WeightsBlob_MetadataEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *WeightsBlob_MetadataEntry) Reset() {
	*x = WeightsBlob_MetadataEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_weights_weights_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WeightsBlob_MetadataEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightsBlob_MetadataEntry) ProtoMessage() {}

func (x *WeightsBlob_MetadataEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightsBlob_MetadataEntry.ProtoReflect.Descriptor instead.
func (*WeightsBlob_MetadataEntry) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{4, 0}
}

func (x *WeightsBlob_MetadataEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WeightsBlob_MetadataEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_proto_weights_weights_proto protoreflect.FileDescriptor

var file_proto_weights_weights_proto_rawDesc = []byte{
		10, 27, 112, 114, 111, 116, 111, 47, 119, 101, 105, 103,
		104, 116, 115, 47, 119, 101, 105, 103, 104, 116, 115, 46,
		112, 114, 111, 116, 111, 18, 20, 99, 97, 114, 116, 114,
		105, 100, 103, 101, 46, 119, 101, 105, 103, 104, 116, 115,
		46, 118, 49, 26, 31, 103, 111, 111, 103, 108, 101, 47,
		112, 114, 111, 116, 111, 98, 117, 102, 47, 116, 105, 109,
		101, 115, 116, 97, 109, 112, 46, 112, 114, 111, 116, 111,
		34, 251, 2, 10, 21, 80, 117, 98, 108, 105, 115, 104,
		87, 101, 105, 103, 104, 116, 115, 82, 101, 113, 117, 101,
		115, 116, 18, 21, 10, 6, 114, 117, 110, 95, 105, 100,
		24, 1, 32, 1, 40, 9, 82, 5, 114, 117, 110, 73,
		100, 18, 18, 10, 4, 115, 116, 101, 112, 24, 2, 32,
		1, 40, 3, 82, 4, 115, 116, 101, 112, 18, 26, 10,
		8, 99, 104, 101, 99, 107, 115, 117, 109, 24, 3, 32,
		1, 40, 9, 82, 8, 99, 104, 101, 99, 107, 115, 117,
		109, 18, 33, 10, 12, 97, 114, 116, 105, 102, 97, 99,
		116, 95, 117, 114, 105, 24, 4, 32, 1, 40, 9, 82,
		11, 97, 114, 116, 105, 102, 97, 99, 116, 85, 114, 105,
		18, 37, 10, 14, 105, 110, 108, 105, 110, 101, 95, 112,
		97, 121, 108, 111, 97, 100, 24, 5, 32, 1, 40, 12,
		82, 13, 105, 110, 108, 105, 110, 101, 80, 97, 121, 108,
		111, 97, 100, 18, 85, 10, 8, 109, 101, 116, 97, 100,
		97, 116, 97, 24, 6, 32, 3, 40, 11, 50, 57, 46,
		99, 97, 114, 116, 114, 105, 100, 103, 101, 46, 119, 101,
		105, 103, 104, 116, 115, 46, 118, 49, 46, 80, 117, 98,
		108, 105, 115, 104, 87, 101, 105, 103, 104, 116, 115, 82,
		101, 113, 117, 101, 115, 116, 46, 77, 101, 116, 97, 100,
		97, 116, 97, 69, 110, 116, 114, 121, 82, 8, 109, 101,
		116, 97, 100, 97, 116, 97, 18, 61, 10, 12, 112, 117,
		98, 108, 105, 115, 104, 101, 100, 95, 97, 116, 24, 7,
		32, 1, 40, 11, 50, 26, 46, 103, 111, 111, 103, 108,
		101, 46, 112, 114, 111, 116, 111, 98, 117, 102, 46, 84,
		105, 109, 101, 115, 116, 97, 109, 112, 82, 11, 112, 117,
		98, 108, 105, 115, 104, 101, 100, 65, 116, 26, 59, 10,
		13, 77, 101, 116, 97, 100, 97, 116, 97, 69, 110, 116,
		114, 121, 18, 16, 10, 3, 107, 101, 121, 24, 1, 32,
		1, 40, 9, 82, 3, 107, 101, 121, 18, 20, 10, 5,
		118, 97, 108, 117, 101, 24, 2, 32, 1, 40, 9, 82,
		5, 118, 97, 108, 117, 101, 58, 2, 56, 1, 34, 85,
		10, 22, 80, 117, 98, 108, 105, 115, 104, 87, 101, 105,
		103, 104, 116, 115, 82, 101, 115, 112, 111, 110, 115, 101,
		18, 59, 10, 7, 118, 101, 114, 115, 105, 111, 110, 24,
		1, 32, 1, 40, 11, 50, 33, 46, 99, 97, 114, 116,
		114, 105, 100, 103, 101, 46, 119, 101, 105, 103, 104, 116,
		115, 46, 118, 49, 46, 87, 101, 105, 103, 104, 116, 115,
		66, 108, 111, 98, 82, 7, 118, 101, 114, 115, 105, 111,
		110, 34, 77, 10, 15, 87, 97, 116, 99, 104, 82, 117,
		110, 82, 101, 113, 117, 101, 115, 116, 18, 21, 10, 6,
		114, 117, 110, 95, 105, 100, 24, 1, 32, 1, 40, 9,
		82, 5, 114, 117, 110, 73, 100, 18, 35, 10, 13, 114,
		101, 112, 108, 97, 121, 95, 108, 97, 116, 101, 115, 116,
		24, 2, 32, 1, 40, 8, 82, 12, 114, 101, 112, 108,
		97, 121, 76, 97, 116, 101, 115, 116, 34, 42, 10, 17,
		71, 101, 116, 67, 117, 114, 114, 101, 110, 116, 82, 101,
		113, 117, 101, 115, 116, 18, 21, 10, 6, 114, 117, 110,
		95, 105, 100, 24, 1, 32, 1, 40, 9, 82, 5, 114,
		117, 110, 73, 100, 34, 231, 2, 10, 11, 87, 101, 105,
		103, 104, 116, 115, 66, 108, 111, 98, 18, 21, 10, 6,
		114, 117, 110, 95, 105, 100, 24, 1, 32, 1, 40, 9,
		82, 5, 114, 117, 110, 73, 100, 18, 18, 10, 4, 115,
		116, 101, 112, 24, 2, 32, 1, 40, 3, 82, 4, 115,
		116, 101, 112, 18, 26, 10, 8, 99, 104, 101, 99, 107,
		115, 117, 109, 24, 3, 32, 1, 40, 9, 82, 8, 99,
		104, 101, 99, 107, 115, 117, 109, 18, 33, 10, 12, 97,
		114, 116, 105, 102, 97, 99, 116, 95, 117, 114, 105, 24,
		4, 32, 1, 40, 9, 82, 11, 97, 114, 116, 105, 102,
		97, 99, 116, 85, 114, 105, 18, 37, 10, 14, 105, 110,
		108, 105, 110, 101, 95, 112, 97, 121, 108, 111, 97, 100,
		24, 5, 32, 1, 40, 12, 82, 13, 105, 110, 108, 105,
		110, 101, 80, 97, 121, 108, 111, 97, 100, 18, 75, 10,
		8, 109, 101, 116, 97, 100, 97, 116, 97, 24, 6, 32,
		3, 40, 11, 50, 47, 46, 99, 97, 114, 116, 114, 105,
		100, 103, 101, 46, 119, 101, 105, 103, 104, 116, 115, 46,
		118, 49, 46, 87, 101, 105, 103, 104, 116, 115, 66, 108,
		111, 98, 46, 77, 101, 116, 97, 100, 97, 116, 97, 69,
		110, 116, 114, 121, 82, 8, 109, 101, 116, 97, 100, 97,
		116, 97, 18, 61, 10, 12, 112, 117, 98, 108, 105, 115,
		104, 101, 100, 95, 97, 116, 24, 7, 32, 1, 40, 11,
		50, 26, 46, 103, 111, 111, 103, 108, 101, 46, 112, 114,
		111, 116, 111, 98, 117, 102, 46, 84, 105, 109, 101, 115,
		116, 97, 109, 112, 82, 11, 112, 117, 98, 108, 105, 115,
		104, 101, 100, 65, 116, 26, 59, 10, 13, 77, 101, 116,
		97, 100, 97, 116, 97, 69, 110, 116, 114, 121, 18, 16,
		10, 3, 107, 101, 121, 24, 1, 32, 1, 40, 9, 82,
		3, 107, 101, 121, 18, 20, 10, 5, 118, 97, 108, 117,
		101, 24, 2, 32, 1, 40, 9, 82, 5, 118, 97, 108,
		117, 101, 58, 2, 56, 1, 50, 180, 2, 10, 14, 87,
		101, 105, 103, 104, 116, 115, 83, 101, 114, 118, 105, 99,
		101, 18, 107, 10, 14, 80, 117, 98, 108, 105, 115, 104,
		87, 101, 105, 103, 104, 116, 115, 18, 43, 46, 99, 97,
		114, 116, 114, 105, 100, 103, 101, 46, 119, 101, 105, 103,
		104, 116, 115, 46, 118, 49, 46, 80, 117, 98, 108, 105,
		115, 104, 87, 101, 105, 103, 104, 116, 115, 82, 101, 113,
		117, 101, 115, 116, 26, 44, 46, 99, 97, 114, 116, 114,
		105, 100, 103, 101, 46, 119, 101, 105, 103, 104, 116, 115,
		46, 118, 49, 46, 80, 117, 98, 108, 105, 115, 104, 87,
		101, 105, 103, 104, 116, 115, 82, 101, 115, 112, 111, 110,
		115, 101, 18, 91, 10, 13, 83, 116, 114, 101, 97, 109,
		87, 101, 105, 103, 104, 116, 115, 18, 37, 46, 99, 97,
		114, 116, 114, 105, 100, 103, 101, 46, 119, 101, 105, 103,
		104, 116, 115, 46, 118, 49, 46, 87, 97, 116, 99, 104,
		82, 117, 110, 82, 101, 113, 117, 101, 115, 116, 26, 33,
		46, 99, 97, 114, 116, 114, 105, 100, 103, 101, 46, 119,
		101, 105, 103, 104, 116, 115, 46, 118, 49, 46, 87, 101,
		105, 103, 104, 116, 115, 66, 108, 111, 98, 48, 1, 18,
		88, 10, 10, 71, 101, 116, 67, 117, 114, 114, 101, 110,
		116, 18, 39, 46, 99, 97, 114, 116, 114, 105, 100, 103,
		101, 46, 119, 101, 105, 103, 104, 116, 115, 46, 118, 49,
		46, 71, 101, 116, 67, 117, 114, 114, 101, 110, 116, 82,
		101, 113, 117, 101, 115, 116, 26, 33, 46, 99, 97, 114,
		116, 114, 105, 100, 103, 101, 46, 119, 101, 105, 103, 104,
		116, 115, 46, 118, 49, 46, 87, 101, 105, 103, 104, 116,
		115, 66, 108, 111, 98, 66, 52, 90, 50, 103, 105, 116,
		104, 117, 98, 46, 99, 111, 109, 47, 99, 97, 114, 116,
		114, 105, 100, 103, 101, 47, 119, 101, 105, 103, 104, 116,
		115, 47, 105, 110, 116, 101, 114, 110, 97, 108, 47, 112,
		98, 59, 119, 101, 105, 103, 104, 116, 115, 112, 98, 98,
		6, 112, 114, 111, 116, 111, 51,
}

var (
	file_proto_weights_weights_proto_rawDescOnce sync.Once
	file_proto_weights_weights_proto_rawDescData = file_proto_weights_weights_proto_rawDesc
)

func file_proto_weights_weights_proto_rawDescGZIP() []byte {
	file_proto_weights_weights_proto_rawDescOnce.Do(func() {
		file_proto_weights_weights_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_weights_weights_proto_rawDescData)
	})
	return file_proto_weights_weights_proto_rawDescData
}

var file_proto_weights_weights_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_weights_weights_proto_goTypes = []interface{}{
	(*PublishWeightsRequest)(nil),               // 0: cartridge.weights.v1.PublishWeightsRequest
	(*PublishWeightsResponse)(nil),              // 1: cartridge.weights.v1.PublishWeightsResponse
	(*WatchRunRequest)(nil),                     // 2: cartridge.weights.v1.WatchRunRequest
	(*GetCurrentRequest)(nil),                   // 3: cartridge.weights.v1.GetCurrentRequest
	(*WeightsBlob)(nil),                         // 4: cartridge.weights.v1.WeightsBlob
	(*PublishWeightsRequest_MetadataEntry)(nil), // 5: cartridge.weights.v1.PublishWeightsRequest.MetadataEntry
	(*WeightsBlob_MetadataEntry)(nil),           // 6: cartridge.weights.v1.WeightsBlob.MetadataEntry
	(*timestamppb.Timestamp)(nil),               // 7: google.protobuf.Timestamp
}
var file_proto_weights_weights_proto_depIdxs = []int32{
	5, // 0: cartridge.weights.v1.PublishWeightsRequest.metadata:type_name -> cartridge.weights.v1.PublishWeightsRequest.MetadataEntry
	7, // 1: cartridge.weights.v1.PublishWeightsRequest.published_at:type_name -> google.protobuf.Timestamp
	4, // 2: cartridge.weights.v1.PublishWeightsResponse.version:type_name -> cartridge.weights.v1.WeightsBlob
	6, // 3: cartridge.weights.v1.WeightsBlob.metadata:type_name -> cartridge.weights.v1.WeightsBlob.MetadataEntry
	7, // 4: cartridge.weights.v1.WeightsBlob.published_at:type_name -> google.protobuf.Timestamp
	0, // 5: cartridge.weights.v1.WeightsService.PublishWeights:input_type -> cartridge.weights.v1.PublishWeightsRequest
	2, // 6: cartridge.weights.v1.WeightsService.StreamWeights:input_type -> cartridge.weights.v1.WatchRunRequest
	3, // 7: cartridge.weights.v1.WeightsService.GetCurrent:input_type -> cartridge.weights.v1.GetCurrentRequest
	1, // 8: cartridge.weights.v1.WeightsService.PublishWeights:output_type -> cartridge.weights.v1.PublishWeightsResponse
	4, // 9: cartridge.weights.v1.WeightsService.StreamWeights:output_type -> cartridge.weights.v1.WeightsBlob
	4, // 10: cartridge.weights.v1.WeightsService.GetCurrent:output_type -> cartridge.weights.v1.WeightsBlob
	9, // [9:11] is the sub-list for method output_type
	5, // [5:9] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_weights_weights_proto_init() }
func file_proto_weights_weights_proto_init() {
	if File_proto_weights_weights_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_weights_weights_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishWeightsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weights_weights_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishWeightsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weights_weights_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchRunRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weights_weights_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weights_weights_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeightsBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weights_weights_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PublishWeightsRequest_MetadataEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_weights_weights_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WeightsBlob_MetadataEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_proto_weights_weights_proto_msgTypes[5].OneofWrappers = nil
	file_proto_weights_weights_proto_msgTypes[6].OneofWrappers = nil

	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_weights_weights_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weights_weights_proto_goTypes,
		DependencyIndexes: file_proto_weights_weights_proto_depIdxs,
		MessageInfos:      file_proto_weights_weights_proto_msgTypes,
	}.Build()

	File_proto_weights_weights_proto = out.File
	file_proto_weights_weights_proto_rawDesc = nil
	file_proto_weights_weights_proto_goTypes = nil
	file_proto_weights_weights_proto_depIdxs = nil
}
