// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/weights/weights.proto

package weightspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WeightsService_PublishWeights_FullMethodName = "/cartridge.weights.v1.WeightsService/PublishWeights"
	WeightsService_StreamWeights_FullMethodName  = "/cartridge.weights.v1.WeightsService/StreamWeights"
	WeightsService_GetCurrent_FullMethodName     = "/cartridge.weights.v1.WeightsService/GetCurrent"
)

// WeightsServiceClient is the client API for WeightsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WeightsService exposes APIs for publishing and consuming learner checkpoints.
type WeightsServiceClient interface {
	// PublishWeights promotes a new weight version for a run.
	PublishWeights(ctx context.Context, in *PublishWeightsRequest, opts ...grpc.CallOption) (*PublishWeightsResponse, error)
	// StreamWeights streams subsequent versions for the requested run.
	StreamWeights(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeightsBlob], error)
	// GetCurrent returns the latest published version for the run.
	GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*WeightsBlob, error)
}

type weightsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWeightsServiceClient(cc grpc.ClientConnInterface) WeightsServiceClient {
	return &weightsServiceClient{cc}
}

func (c *weightsServiceClient) PublishWeights(ctx context.Context, in *PublishWeightsRequest, opts ...grpc.CallOption) (*PublishWeightsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishWeightsResponse)
	err := c.cc.Invoke(ctx, WeightsService_PublishWeights_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weightsServiceClient) StreamWeights(ctx context.Context, in *WatchRunRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WeightsBlob], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WeightsService_ServiceDesc.Streams[0], WeightsService_StreamWeights_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRunRequest, WeightsBlob]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WeightsService_StreamWeightsClient = grpc.ServerStreamingClient[WeightsBlob]

func (c *weightsServiceClient) GetCurrent(ctx context.Context, in *GetCurrentRequest, opts ...grpc.CallOption) (*WeightsBlob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeightsBlob)
	err := c.cc.Invoke(ctx, WeightsService_GetCurrent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeightsServiceServer is the server API for WeightsService service.
// All implementations must embed UnimplementedWeightsServiceServer
// for forward compatibility.
//
// WeightsService exposes APIs for publishing and consuming learner checkpoints.
type WeightsServiceServer interface {
	// PublishWeights promotes a new weight version for a run.
	PublishWeights(context.Context, *PublishWeightsRequest) (*PublishWeightsResponse, error)
	// StreamWeights streams subsequent versions for the requested run.
	StreamWeights(*WatchRunRequest, grpc.ServerStreamingServer[WeightsBlob]) error
	// GetCurrent returns the latest published version for the run.
	GetCurrent(context.Context, *GetCurrentRequest) (*WeightsBlob, error)
	mustEmbedUnimplementedWeightsServiceServer()
}

// UnimplementedWeightsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWeightsServiceServer struct{}

func (UnimplementedWeightsServiceServer) PublishWeights(context.Context, *PublishWeightsRequest) (*PublishWeightsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishWeights not implemented")
}
func (UnimplementedWeightsServiceServer) StreamWeights(*WatchRunRequest, grpc.ServerStreamingServer[WeightsBlob]) error {
	return status.Errorf(codes.Unimplemented, "method StreamWeights not implemented")
}
func (UnimplementedWeightsServiceServer) GetCurrent(context.Context, *GetCurrentRequest) (*WeightsBlob, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrent not implemented")
}
func (UnimplementedWeightsServiceServer) mustEmbedUnimplementedWeightsServiceServer() {}
func (UnimplementedWeightsServiceServer) testEmbeddedByValue()                        {}

// UnsafeWeightsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeightsServiceServer will
// result in compilation errors.
type UnsafeWeightsServiceServer interface {
	mustEmbedUnimplementedWeightsServiceServer()
}

func RegisterWeightsServiceServer(s grpc.ServiceRegistrar, srv WeightsServiceServer) {
	// If the following call pancis, it indicates UnimplementedWeightsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WeightsService_ServiceDesc, srv)
}

func _WeightsService_PublishWeights_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishWeightsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServiceServer).PublishWeights(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeightsService_PublishWeights_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServiceServer).PublishWeights(ctx, req.(*PublishWeightsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeightsService_StreamWeights_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRunRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WeightsServiceServer).StreamWeights(m, &grpc.GenericServerStream[WatchRunRequest, WeightsBlob]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WeightsService_StreamWeightsServer = grpc.ServerStreamingServer[WeightsBlob]

func _WeightsService_GetCurrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeightsServiceServer).GetCurrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeightsService_GetCurrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeightsServiceServer).GetCurrent(ctx, req.(*GetCurrentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeightsService_ServiceDesc is the grpc.ServiceDesc for WeightsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeightsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cartridge.weights.v1.WeightsService",
	HandlerType: (*WeightsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishWeights",
			Handler:    _WeightsService_PublishWeights_Handler,
		},
		{
			MethodName: "GetCurrent",
			Handler:    _WeightsService_GetCurrent_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamWeights",
			Handler:       _WeightsService_StreamWeights_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/weights/weights.proto",
}
