// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: proto/weights/weights.proto

package weightspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PublishWeightsRequest carries learner output metadata.
type PublishWeightsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          int64                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ArtifactUri   string                 `protobuf:"bytes,4,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	InlinePayload []byte                 `protobuf:"bytes,5,opt,name=inline_payload,json=inlinePayload,proto3" json:"inline_payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishWeightsRequest) Reset() {
	*x = PublishWeightsRequest{}
	mi := &file_proto_weights_weights_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishWeightsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWeightsRequest) ProtoMessage() {}

func (x *PublishWeightsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWeightsRequest.ProtoReflect.Descriptor instead.
func (*PublishWeightsRequest) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{0}
}

func (x *PublishWeightsRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *PublishWeightsRequest) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *PublishWeightsRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *PublishWeightsRequest) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *PublishWeightsRequest) GetInlinePayload() []byte {
	if x != nil {
		return x.InlinePayload
	}
	return nil
}

func (x *PublishWeightsRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *PublishWeightsRequest) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

// PublishWeightsResponse acknowledges a publication.
type PublishWeightsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       *WeightsBlob           `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishWeightsResponse) Reset() {
	*x = PublishWeightsResponse{}
	mi := &file_proto_weights_weights_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishWeightsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishWeightsResponse) ProtoMessage() {}

func (x *PublishWeightsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishWeightsResponse.ProtoReflect.Descriptor instead.
func (*PublishWeightsResponse) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{1}
}

func (x *PublishWeightsResponse) GetVersion() *WeightsBlob {
	if x != nil {
		return x.Version
	}
	return nil
}

// WatchRunRequest opens a stream for updates.
type WatchRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	ReplayLatest  bool                   `protobuf:"varint,2,opt,name=replay_latest,json=replayLatest,proto3" json:"replay_latest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRunRequest) Reset() {
	*x = WatchRunRequest{}
	mi := &file_proto_weights_weights_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRunRequest) ProtoMessage() {}

func (x *WatchRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRunRequest.ProtoReflect.Descriptor instead.
func (*WatchRunRequest) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{2}
}

func (x *WatchRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WatchRunRequest) GetReplayLatest() bool {
	if x != nil {
		return x.ReplayLatest
	}
	return false
}

// GetCurrentRequest fetches the latest version.
type GetCurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrentRequest) Reset() {
	*x = GetCurrentRequest{}
	mi := &file_proto_weights_weights_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentRequest) ProtoMessage() {}

func (x *GetCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentRequest) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// WeightsBlob represents a published manifest.
type WeightsBlob struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Step          int64                  `protobuf:"varint,2,opt,name=step,proto3" json:"step,omitempty"`
	Checksum      string                 `protobuf:"bytes,3,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ArtifactUri   string                 `protobuf:"bytes,4,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	InlinePayload []byte                 `protobuf:"bytes,5,opt,name=inline_payload,json=inlinePayload,proto3" json:"inline_payload,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	PublishedAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeightsBlob) Reset() {
	*x = WeightsBlob{}
	mi := &file_proto_weights_weights_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeightsBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeightsBlob) ProtoMessage() {}

func (x *WeightsBlob) ProtoReflect() protoreflect.Message {
	mi := &file_proto_weights_weights_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeightsBlob.ProtoReflect.Descriptor instead.
func (*WeightsBlob) Descriptor() ([]byte, []int) {
	return file_proto_weights_weights_proto_rawDescGZIP(), []int{4}
}

func (x *WeightsBlob) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WeightsBlob) GetStep() int64 {
	if x != nil {
		return x.Step
	}
	return 0
}

func (x *WeightsBlob) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

func (x *WeightsBlob) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *WeightsBlob) GetInlinePayload() []byte {
	if x != nil {
		return x.InlinePayload
	}
	return nil
}

func (x *WeightsBlob) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *WeightsBlob) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

var File_proto_weights_weights_proto protoreflect.FileDescriptor

const file_proto_weights_weights_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/weights/weights.proto\x12\x14cartridge.weights.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x02\n" +
	"\x15PublishWeightsRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x03R\x04step\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12!\n" +
	"\fartifact_uri\x18\x04 \x01(\tR\vartifactUri\x12%\n" +
	"\x0einline_payload\x18\x05 \x01(\fR\rinlinePayload\x12U\n" +
	"\bmetadata\x18\x06 \x03(\v29.cartridge.weights.v1.PublishWeightsRequest.MetadataEntryR\bmetadata\x12=\n" +
	"\fpublished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\x16PublishWeightsResponse\x12;\n" +
	"\aversion\x18\x01 \x01(\v2!.cartridge.weights.v1.WeightsBlobR\aversion\"M\n" +
	"\x0fWatchRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12#\n" +
	"\rreplay_latest\x18\x02 \x01(\bR\freplayLatest\"*\n" +
	"\x11GetCurrentRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\xe7\x02\n" +
	"\vWeightsBlob\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\x03R\x04step\x12\x1a\n" +
	"\bchecksum\x18\x03 \x01(\tR\bchecksum\x12!\n" +
	"\fartifact_uri\x18\x04 \x01(\tR\vartifactUri\x12%\n" +
	"\x0einline_payload\x18\x05 \x01(\fR\rinlinePayload\x12K\n" +
	"\bmetadata\x18\x06 \x03(\v2/.cartridge.weights.v1.WeightsBlob.MetadataEntryR\bmetadata\x12=\n" +
	"\fpublished_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\xb4\x02\n" +
	"\x0eWeightsService\x12k\n" +
	"\x0ePublishWeights\x12+.cartridge.weights.v1.PublishWeightsRequest\x1a,.cartridge.weights.v1.PublishWeightsResponse\x12[\n" +
	"\rStreamWeights\x12%.cartridge.weights.v1.WatchRunRequest\x1a!.cartridge.weights.v1.WeightsBlob0\x01\x12X\n" +
	"\n" +
	"GetCurrent\x12'.cartridge.weights.v1.GetCurrentRequest\x1a!.cartridge.weights.v1.WeightsBlobB4Z2github.com/cartridge/weights/internal/pb;weightspbb\x06proto3"

var (
	file_proto_weights_weights_proto_rawDescOnce sync.Once
	file_proto_weights_weights_proto_rawDescData []byte
)

func file_proto_weights_weights_proto_rawDescGZIP() []byte {
	file_proto_weights_weights_proto_rawDescOnce.Do(func() {
		file_proto_weights_weights_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_weights_weights_proto_rawDesc), len(file_proto_weights_weights_proto_rawDesc)))
	})
	return file_proto_weights_weights_proto_rawDescData
}

var file_proto_weights_weights_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_weights_weights_proto_goTypes = []any{
	(*PublishWeightsRequest)(nil),  // 0: cartridge.weights.v1.PublishWeightsRequest
	(*PublishWeightsResponse)(nil), // 1: cartridge.weights.v1.PublishWeightsResponse
	(*WatchRunRequest)(nil),        // 2: cartridge.weights.v1.WatchRunRequest
	(*GetCurrentRequest)(nil),      // 3: cartridge.weights.v1.GetCurrentRequest
	(*WeightsBlob)(nil),            // 4: cartridge.weights.v1.WeightsBlob
	nil,                            // 5: cartridge.weights.v1.PublishWeightsRequest.MetadataEntry
	nil,                            // 6: cartridge.weights.v1.WeightsBlob.MetadataEntry
	(*timestamppb.Timestamp)(nil),  // 7: google.protobuf.Timestamp
}
var file_proto_weights_weights_proto_depIdxs = []int32{
	5, // 0: cartridge.weights.v1.PublishWeightsRequest.metadata:type_name -> cartridge.weights.v1.PublishWeightsRequest.MetadataEntry
	7, // 1: cartridge.weights.v1.PublishWeightsRequest.published_at:type_name -> google.protobuf.Timestamp
	4, // 2: cartridge.weights.v1.PublishWeightsResponse.version:type_name -> cartridge.weights.v1.WeightsBlob
	6, // 3: cartridge.weights.v1.WeightsBlob.metadata:type_name -> cartridge.weights.v1.WeightsBlob.MetadataEntry
	7, // 4: cartridge.weights.v1.WeightsBlob.published_at:type_name -> google.protobuf.Timestamp
	0, // 5: cartridge.weights.v1.WeightsService.PublishWeights:input_type -> cartridge.weights.v1.PublishWeightsRequest
	2, // 6: cartridge.weights.v1.WeightsService.StreamWeights:input_type -> cartridge.weights.v1.WatchRunRequest
	3, // 7: cartridge.weights.v1.WeightsService.GetCurrent:input_type -> cartridge.weights.v1.GetCurrentRequest
	1, // 8: cartridge.weights.v1.WeightsService.PublishWeights:output_type -> cartridge.weights.v1.PublishWeightsResponse
	4, // 9: cartridge.weights.v1.WeightsService.StreamWeights:output_type -> cartridge.weights.v1.WeightsBlob
	4, // 10: cartridge.weights.v1.WeightsService.GetCurrent:output_type -> cartridge.weights.v1.WeightsBlob
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_weights_weights_proto_init() }
func file_proto_weights_weights_proto_init() {
	if File_proto_weights_weights_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_weights_weights_proto_rawDesc), len(file_proto_weights_weights_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_weights_weights_proto_goTypes,
		DependencyIndexes: file_proto_weights_weights_proto_depIdxs,
		MessageInfos:      file_proto_weights_weights_proto_msgTypes,
	}.Build()
	File_proto_weights_weights_proto = out.File
	file_proto_weights_weights_proto_goTypes = nil
	file_proto_weights_weights_proto_depIdxs = nil
}
