[package]
name = "cartridge-observability"
version = "0.1.0"
edition = "2021"

[dependencies]
# Observability
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
metrics-exporter-prometheus = { workspace = true }
once_cell = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }
